### ISSUE TITLE
Add user story to readme

### ISSUE THREAD

**Issue by JAlexander94** [JAlexander94/Project-JJJ#1]

**Comment by stillawake17** [comment]
I'm going to add the User Story on the ReadMe file on a separate branch:

Using the Police API and the Zoopla API, 

User Story 

A person looking for a house to buy comes to our website YourHood and searches by location or postcode. 

They get a list of houses available to buy, according to certain criteria they've chosen. They also have the choice to look at police data about the crime in the area. 

The user will have fulfilled their search criteria once they can search for houses in a particular area, by post code or location;

The user will have fulfilled their search when they know the crime levels in the neighbourhood.

The user gets the house price, details about the house [[number of bedrooms, bathrooms, garden or not, pictures]] and the neighbourhood information about the crime levels.

Additional:
They could also reverse search from areas with a certain level of crime and link that back to houses available to purchase.

Bonus:
They can book a viewing with the estate agent.

**Comment by stillawake17** [comment]
I have added a commit for the ReadMe but I think it needs to be reviewed.
