### ISSUE TITLE
create wireframe for the site

### ISSUE THREAD

**Issue by JAlexander94** [JAlexander94/Project-JJJ#2]

**Comment by Jmotsi** [comment]
![image_720](https://user-images.githubusercontent.com/102466210/218183744-0fb0240b-692c-4272-92c6-c21e751655e1.png)
![image_720](https://user-images.githubusercontent.com/102466210/218183770-65ab9264-15fb-41ba-a739-69b0c3782705.png)

wireframe has been completed
